### ISSUE TITLE
Missing text in uaa spec

### ISSUE THREAD

**Issue by APShirley** [cloudfoundry/uaa-release#25]
It seems like there are some missing words on [line 95](https://github.com/cloudfoundry/uaa-release/blob/develop/jobs/uaa/spec#L95) of the `uaa/template/spec`.

"If this property" (is set?) "Tomcat will listen to..."

``` yaml
uaa.ssl.port:
    description: If this property Tomcat will listen to this port and expect https traffic. If null, tomcat will not listen to this port
    default: 8443
```
