### ISSUE TITLE
Postgres passwords aren't escaped

### ISSUE THREAD

**Issue by iredelmeier** [cloudfoundry/uaa-release#47]
Hi there!

This bug is kind of a weird edge case.

Given a manifest including:

```yaml
jobs:
- name: uaa_postgres
  release: uaa
  properties:
    postgres:
      address: 127.0.0.1
      port: 5432
      databases:
      - tag: uaa
        name: uaa
      roles:
      - tag: admin
        name: postgres
        password: bad"password`
```

Then `postgres_start.sh` will fail to create the `postgres` role due to the unescaped password.

I can submit a PR for this if you want.

Thanks!
