### ISSUE TITLE
Error in manifest property definition for authorized-grant-types is hard to debug

### ISSUE THREAD

**Issue by genevievelesperance** [cloudfoundry/uaa-release#48]
Client authorized grant types may be specified in the bosh deployment manifest as `authorized-grant-types`.

We incorrectly wrote this property as `authorized_grant_types` (underscore instead of dash).

Surprisingly, this manifest deployed correctly, and even `uaac client get` shows the the grant types that we asked for:

```
uaac client get network-policy
  scope: uaa.none
  client_id: network-policy
  resource_ids: none
  authorized_grant_types: client_credentials
  autoapprove:
  authorities: uaa.resource cloud_controller.admin_read_only
  lastmodified: 1485209371083
```

However, those grant types do not actually work.

```
uaac token client get network-policy
Client secret:  *********************

error response:
{
  "error": "invalid_client",
  "error_description": "Unauthorized grant type: client_credentials"
}
attempt to get token failed
```

If we fix our manifest to instead have the correct `authorized-grant-types` property:

```diff
properties:
  uaa:
    clients:
      network-policy:
-       authorized_grant_types: client_credentials
+       authorized-grant-types: client_credentials
```

then the deploy succeeds and we're actually able to use the client credentials to fetch a token:

```
uaac token client get network-policy
Client secret:  *********************

Successfully fetched token via client credentials grant.
Target: https://uaa.bosh-lite.com
Context: network-policy, from client network-policy
```

cc @rosenhouse
