### ISSUE TITLE
Unable to integrate AWS AD with UAA

### ISSUE THREAD

**Issue by lordcf** [cloudfoundry/uaa-release#66]
I am able to integrate local LDAP server with CF uaa component. But I want to use AWS Simple AD user to be able to authenticate into CF.
I have added following properties:-
ldap:
      enabled: true
      mailAttributeName: mail
      profile_type: search-and-bind
      searchBase: "dc=example,dc=com" (directory domain)
      searchFilter: cn={0}
      url: ldap://private-dns-ip-of-AD 
      userDN: "CN=Administrator,cn=Users,dc=example,dc=com"
      userPassword: "Password for admin user"

But still those users are not able to authenticate with CF. There are no logs available related to this on uaa VM, neither user entries in uaadb. Configurations are same as I did for local LDAP server. 
Am I missing any configuration?

**Comment by tnwang** [comment]
Log entries would appear in the UAA VM when you attempt to login to a user from the login page, which should give you a hint at what's happening. Keep in mind that if you have a local user with the same username as an LDAP, it will be authenticated locally first and UAA will not attempt to bind to LDAP.

Your configurations look fine. I think formatting got lost, so make sure to nest the configurations, like below:
```
      uaa:
        ldap:
          enabled: true
          groups:
            profile_type: groups-map-to-scopes
            searchBase: ou=scopes,dc=test,dc=com
          profile_type: search-and-bind
          searchBase: dc=test,dc=com
          searchFilter: cn={0}
          url: ldap://1.2.3.4:389/
          userDN: cn=youruser
          userPassword: password
```
